import os
from typing import List
from pydantic import BaseModel, Field
from pydantic_ai import Agent
from pydantic_ai.models.google import GoogleModel
from langfuse.decorators import observe
from src.core.config import settings

# 1. ENVIRONMENT CONFIGURATION
# PydanticAI requires GOOGLE_API_KEY in os.environ
os.environ["GOOGLE_API_KEY"] = settings.gemini_api_key

# 2. DATA MODELS (Structured Output)
class PlatformPost(BaseModel):
    """Single content optimized for given platform's algorithm."""
    platform: str = Field(description="TikTok, YouTube or LinkedIn")
    content: str = Field(description="Full post content including hook and CTA")
    hashtags: List[str] = Field(description="List of targeted hashtags")

class ClipStrategy(BaseModel):
    """Marketing strategy for single video fragment."""
    clip_index: int = Field(description="Sequential number of clip from analysis")
    duration_seconds: int = Field(description="Clip length in seconds")
    posts: List[PlatformPost] = Field(description="Content variants for platforms")

class CampaignBrief(BaseModel):
    """Final marketing strategy generated by the Agent."""
    overall_strategy: str = Field(description="Main idea and tone of campaign")
    clip_strategies: List[ClipStrategy] = Field(description="Detailed posts for each clip")

# 3. ENGINE AND AGENT INITIALIZATION
# We use the gemini-3-flash-preview model
model = GoogleModel('gemini-3-flash-preview')

copywriter_agent = Agent(
    model=model,
    output_type=CampaignBrief,
    system_prompt=(
        "You are the Chief Strategy Officer at OPERATORS' FORGE. Your goal is to maximize reach while maintaining absolute consistency with the visuals.\n\n"
        
        "YOUR TOOLS:\n"
        "You will receive a 'VideoAnalysisReport'. You must use the 'visual_description' and 'narrative_hook' fields contained within "
        "to prove to the viewer that the description relates exactly to what they see on screen.\n\n"
        
        "LENGTH LOGIC (Critical):\n"
        "- Clips < 15s: Apply 'Ultra-Short-Impact'. One provocative hook, no introduction, immediate CTA.\n"
        "- Clips 15-60s: Add one substantive Insight resulting from the action in the video before CTA.\n\n"
        
        "PLATFORM REQUIREMENTS:\n"
        "1. TikTok/Reels: Aggressive style, 'fast-paced', use engineering slang, strong visual hook at the start.\n"
        "2. YouTube Shorts: SEO-friendly, clear value promise, write what the viewer will gain by watching the whole thing.\n"
        "3. LinkedIn: Expert tone, storytelling based on technology visible in the clip. Build OPERATORS' FORGE authority.\n\n"
        
        "CRITICAL RULE: If the video shows robots, write about robotics. If it shows drones, write about drones. "
        "Never assume the topic in advance. Adapt Forge values to the video context.\n"
        "Write exclusively in English."
    )
)

# 4. OPERATIONAL LOGIC
@observe(name="Agent_Copywriter_Run")
async def run_copywriting(analysis_data: dict) -> CampaignBrief:
    """Transforms analytical data into complete post campaign."""
    
    print("LOG: Gemini 3 Flash Preview generating strategy and social media posts...")
    
    result = await copywriter_agent.run(
        f"Prepare marketing campaign based on the following analytical data: {analysis_data}"
    )
    
    # According to version 1.39.0 the result is in .output
    return result.output